# Generated by Django 2.2.14 on 2020-12-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_home', '0026_item_deals_of_the_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='deals_of_the_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deals_of_the_day_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
